### ISSUE TITLE
New update works on the main branch. But? can't backspace.

### ISSUE THREAD

**Issue by Nllii** [lpenz/tuzue#1]
It's finally working.  
Thanks for the new update.  Commit  4d7aa8a27315801ac8a5f9682a16e4855bb411e2 works.

Tested on mac:
Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; RELEASE_X86_64 x86_64

issues: 
- can't delete or backspace on mac os x 10.15.7 (19H114)
reference to commit c2c291c78506853da8e5c063c097592147a65cc6

did the test pass?
**Yes it did.**
<img width="1057" alt="Screen Shot 2022-10-31 at 4 14 55 AM" src="https://user-images.githubusercontent.com/5082827/198974356-d43ecee0-d62c-4356-9190-24ebac3eee21.png">

https://github.com/lpenz/tuzue/blob/7a6abce357abb64c56cba9123495463836757e01/tests/test_input.py#L19

Great work. Im updating my code to use your project. I was using https://github.com/wong2/pick.

**Comment by lpenz** [comment]
Hey, I'm glad it's been useful.

The tests exercise the behavior of the key presses, but not their recognition - i.e. they check that a backspace will delete the character to the left, but not that we identify that backspace was pressed. That leads to the conclusion that the identification of the key press is the issue. We use `curses.keyname`  to figure out which key was pressed, in https://github.com/lpenz/tuzue/blob/7a6abce357abb64c56cba9123495463836757e01/src/tuzue/ui/curses.py#L183 - it should have returned the name `KEY_BACKSPACE`

I also found a stackoverflow question about this: https://stackoverflow.com/questions/47481955/python-curses-detecting-the-backspace-key - maybe it works in a different terminal?

Unfortunately, I don't have a mac to debug this.

**Comment by Nllii** [comment]
Thank you for your comment. I fixed it.
